import { getActiveLanguage } from 'laravel-vue-i18n';

type Catalog = Record<string, string>;

/**
 * Every translation catalog, bundled at build time (no request at runtime).
 * `lang/{locale}.json` holds the app strings; `lang/php_{locale}.json` is
 * generated by the laravel-vue-i18n Vite plugin from Laravel's PHP files
 * (validation, auth, passwords).
 */
const catalogs = import.meta.glob<{ default: Catalog }>(
    '../../../lang/*.json',
    {
        eager: true,
    },
);

export function resolveLanguage(locale: string): Catalog {
    return catalogs[`../../../lang/${locale}.json`]?.default ?? {};
}

/** The active locale as a BCP 47 tag for `Intl` (`fr_BE` → `fr-BE`). */
export function languageTag(): string {
    return getActiveLanguage().replace('_', '-');
}

/** A date and time in the active language, e.g. "30 sept. 2026, 21:14". */
export function formatDateTime(timestamp: string): string {
    return new Intl.DateTimeFormat(languageTag(), {
        dateStyle: 'medium',
        timeStyle: 'short',
    }).format(new Date(timestamp));
}

/** A number in the active language, e.g. "1 262" / "1,262". */
export function formatNumber(value: number): string {
    return new Intl.NumberFormat(languageTag()).format(value);
}
